### ISSUE TITLE
На экране детали вакансии сердечко (избраннное) слишком близко к краю экрана, должно быть 20

### ISSUE THREAD

**Issue by alexxk2** [menta1/practicum-android-diploma#119]

**Comment by ImNia** [comment]
На экране с описанием вакансии, хорошо бы поправить верстку всей верхней строки, из-за того что элементы заданы относительно друг друга, у стрелки назад отступ отличается от отступа на экране с похожими вакансиями, и при переходе, кажется что стрелки прыгают
